FROM node:26.3.1@sha256:3c05c2cf0f6a5795dfb7abefb2a4e31a78d6271a99962531c48315ced17d618a

WORKDIR /app/ui

COPY ui /app/ui

RUN npm install -g corepack@0.34.6 && corepack enable && pnpm install --frozen-lockfile

ENTRYPOINT ["pnpm", "start"]

